import keyMirror from 'key-mirror';

export default keyMirror({
  SET_PLATFORM: null,
  SET_VERSION: null,

  LOGOUT: null,
  FORGOT_PASSWORD: null,
  LOGIN: null,
  REGISTER: null,
  VERIFY_EMAIL: null,
  SIGNUP_SOCIAL: null,
  SELECT_LOCATION: null,

  ON_AUTH_FORM_FIELD_CHANGE: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  SIGNUP_SOCIAL_REQUEST: null,
  SIGNUP_SOCIAL_SUCCESS: null,
  SIGNUP_SOCIAL_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  VERIFY_EMAIL_REQUEST: null,
  VERIFY_EMAIL_SUCCESS: null,
  VERIFY_EMAIL_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null,

  CHECK_OR_CREATE_NEW_USER_REQUEST: null,
  CHECK_OR_CREATE_NEW_USER_SUCCESS: null,
  CHECK_OR_CREATE_NEW_USER_FAILURE: null,

  GET_USER_INFO_REQUEST: null,
  GET_USER_INFO_SUCCESS: null,
  GET_USER_INFO_FAILURE: null,

  SET_USER_INFO_REQUEST: null,
  SET_USER_INFO_SUCCESS: null,
  SET_USER_INFO_FAILURE: null,

  DELETE_USER_REQUEST: null,
  DELETE_USER_SUCCESS: null,
  DELETE_USER_FAILURE: null,

  DELETE_USER_DATA_REQUEST: null,
  DELETE_USER_DATA_SUCCESS: null,
  DELETE_USER_DATA_FAILURE: null,

  GET_AREAS_REQUEST: null,
  GET_AREAS_SUCCESS: null,
  GET_AREAS_FAILURE: null,

  GET_WAREHOUSES_REQUEST: null,
  GET_WAREHOUSES_SUCCESS: null,
  GET_WAREHOUSES_FAILURE: null,

  GET_TIME_SLOTS_REQUEST: null,
  GET_TIME_SLOTS_SUCCESS: null,
  GET_TIME_SLOTS_FAILURE: null,

  SET_TIME_SLOTS_REQUEST: null,
  SET_TIME_SLOTS_SUCCESS: null,
  SET_TIME_SLOTS_FAILURE: null,

  GET_PAYMENT_METHODS_REQUEST: null,
  GET_PAYMENT_METHODS_SUCCESS: null,
  GET_PAYMENT_METHODS_FAILURE: null,

  GET_DELIVERY_VARIANTS_REQUEST: null,
  GET_DELIVERY_VARIANTS_SUCCESS: null,
  GET_DELIVERY_VARIANTS_FAILURE: null,

  SAVE_AREA_AND_WAREHOUSE_REQUEST: null,
  SAVE_AREA_AND_WAREHOUSE_SUCCESS: null,
  SAVE_AREA_AND_WAREHOUSE_FAILURE: null,

  GET_GROUPS_SHOP_REQUEST: null,
  GET_GROUPS_SHOP_SUCCESS: null,
  GET_GROUPS_SHOP_FAILURE: null,

  GET_GROUPS_EXPLORE_REQUEST: null,
  GET_GROUPS_EXPLORE_SUCCESS: null,
  GET_GROUPS_EXPLORE_FAILURE: null,

  GET_GOODS_SHOP_REQUEST: null,
  GET_GOODS_SHOP_SUCCESS: null,
  GET_GOODS_SHOP_FAILURE: null,

  GET_GOODS_EXPLORE_REQUEST: null,
  GET_GOODS_EXPLORE_SUCCESS: null,
  GET_GOODS_EXPLORE_FAILURE: null,

  GET_GOODS_EXPLORE_REMAINS_REQUEST: null,
  GET_GOODS_EXPLORE_REMAINS_SUCCESS: null,
  GET_GOODS_EXPLORE_REMAINS_FAILURE: null,

  GET_GOODS_DETAILS_REQUEST: null,
  GET_GOODS_DETAILS_SUCCESS: null,
  GET_GOODS_DETAILS_FAILURE: null,

  GET_MY_CART_REQUEST: null,
  GET_MY_CART_SUCCESS: null,
  GET_MY_CART_FAILURE: null,

  ADD_TO_CART_REQUEST: null,
  ADD_TO_CART_SUCCESS: null,
  ADD_TO_CART_FAILURE: null,

  GET_FAVORITES_REQUEST: null,
  GET_FAVORITES_SUCCESS: null,
  GET_FAVORITES_FAILURE: null,
  
  ADD_TO_FAVORITES_REQUEST: null,
  ADD_TO_FAVORITES_SUCCESS: null,
  ADD_TO_FAVORITES_FAILURE: null,

  ADD_TO_ORDERS_REQUEST: null,
  ADD_TO_ORDERS_SUCCESS: null,
  ADD_TO_ORDERS_FAILURE: null,
  
  GET_ORDERS_REQUEST: null,
  GET_ORDERS_SUCCESS: null,
  GET_ORDERS_FAILURE: null,

  SEARCH_GOODS_REQUEST: null,
  SEARCH_GOODS_SUCCESS: null,
  SEARCH_GOODS_FAILURE: null,

  SEARCH_GOODS_REMAINS_REQUEST: null,
  SEARCH_GOODS_REMAINS_SUCCESS: null,
  SEARCH_GOODS_REMAINS_FAILURE: null,

  LOGOUT_CLEAR_REQUEST: null,
  LOGOUT_CLEAR_SUCCESS: null,
  LOGOUT_CLEAR_FAILURE: null,

  GET_MESSAGES_REQUEST: null,
  GET_MESSAGES_SUCCESS: null,
  GET_MESSAGES_FAILURE: null,

  SET_MESSAGE_READ_REQUEST: null,
  SET_MESSAGE_READ_SUCCESS: null,
  SET_MESSAGE_READ_FAILURE: null,

  GET_CHAT_REQUEST: null,
  GET_CHAT_SUCCESS: null,
  GET_CHAT_FAILURE: null,

  SET_CHAT_READ_REQUEST: null,
  SET_CHAT_READ_SUCCESS: null,
  SET_CHAT_READ_FAILURE: null,

  ADD_TO_CHAT_REQUEST: null,
  ADD_TO_CHAT_SUCCESS: null,
  ADD_TO_CHAT_FAILURE: null,

  GET_BANNERS_REQUEST: null,
  GET_BANNERS_SUCCESS: null,
  GET_BANNERS_FAILURE: null,


  //-----
});
