/**
 * ## Styles
 */
import { StyleSheet } from "react-native";

import {Dimensions} from 'react-native';
var {height, width} = Dimensions.get('window'); // Screen dimensions in current orientation

var styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    //borderColor: '#000',
    //borderWidth: 1,
  },
  act_container: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  scan_container: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
  },
  forgotContainer: {
    flexDirection: "column",
    justifyContent: "space-between",
  },
  row: {
    flexDirection: "row",
    margin: 10,
    justifyContent: "space-between",
  },
  dark_theme_checkbox: {
    backgroundColor: "lightgray",
  },
  text: {
    color: "#030303",
  },
  text_header: {
    fontSize: 20,
    color: "#046061",
    marginLeft: 25,
  },
  title: {
    marginTop: 45,
    marginBottom: 35,
    marginLeft: 5,
    marginRight: 5,
    color: "#046061",
    textAlign: "center",
  },
  title_paragraph: {
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 25,
    marginRight: 25,
    color: "#4F4F4F",
  },
  title_text_empty: {
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 25,
    marginRight: 25,
    fontSize: 12,
    color: "#4F4F4F",
  },
  title_paragraph_rules: {
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 25,
    marginRight: 25,
    textAlign: "center",
    color: "#4F4F4F",
  },
  title_paragraph_rules_pin: {
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 25,
    marginRight: 25,
    textAlign: "center",
    color: "#4F4F4F",
  },
  text_connection_err: {
    margin: 20,
    fontSize: 18,
    textAlign: "center",
  },
  button: {
    //paddingTop: 9,
    //paddingBottom: 9,
    marginTop: 20,
    marginBottom: 0,
    marginLeft: 25,
    marginRight: 25,
    borderRadius: 19,
    backgroundColor: "#53B175",
  },
  button2: {
    //paddingTop: 9,
    //paddingBottom: 9,
    marginTop: 20,
    marginBottom: 0,
    //marginLeft: 25,
    //marginRight: 25,
    borderRadius: 19,
    backgroundColor: "#53B175",
  },
  button_label: {
    paddingTop: 9,
    paddingBottom: 9,
    fontSize: 14,
    textAlign: "center",
    color: "#FCFCFC",
  },
  button_disabled: {
    //paddingTop: 9,
    //paddingBottom: 9,
    marginTop: 20,
    marginBottom: 0,
    marginLeft: 25,
    marginRight: 25,
    borderRadius: 19,
    backgroundColor: "#F2F3F2",
    //borderColor: "#000",
    //borderWidth: 1,
  },
  button_disabled2: {
    //paddingTop: 9,
    //paddingBottom: 9,
    marginTop: 20,
    marginBottom: 0,
    //marginLeft: 25,
    //marginRight: 25,
    borderRadius: 19,
    backgroundColor: "#F2F3F2",
    //borderColor: "#000",
    //borderWidth: 1,
  },
  button_label_disabled: {
    paddingTop: 9,
    paddingBottom: 9,
    fontSize: 14,
    textAlign: "center",
    color: "#53B175",
  },
  button_signin: {
    //paddingTop: 9,
    //paddingBottom: 9,
    marginTop: 0.0223 * height,
    marginBottom: 0,
    marginLeft: 25,
    marginRight: 25,
    borderRadius: 19,
    backgroundColor: "#5383EC",
  },
  button_signin_label: {
    paddingTop: 9,
    paddingBottom: 9,
    fontSize: 14,
    textAlign: "center",
    color: "white",
  },
  button_signin2: {
    //paddingTop: 9,
    //paddingBottom: 9,
    marginTop: 0.0223 * height,
    marginBottom: 0,
    marginLeft: 25,
    marginRight: 25,
    borderRadius: 19,
    borderColor: "#5383EC",
    borderWidth: 1,
    backgroundColor: "#FCFCFC",
  },
  button_signin_label2: {
    paddingTop: 9,
    paddingBottom: 9,
    fontSize: 14,
    textAlign: "center",
    color: "#5383EC",
  },
  button_text: {
    color: "#ffffff",
    //fontSize: 17,
  },
  button_text_outlined: {
    color: "#828282",
    fontSize: 14,
  },
  button_text_outlined2: {
    color: "#030303",
    fontWeight: "bold",
    fontSize: 14,
  },
  button_text_outlined3: {
    color: "#181725",
    fontSize: 14,
  },
  button_text_outlined4: {
    color: "#53B175",
    fontWeight: "bold",
    fontSize: 14,
  },
  button_second: {
    marginTop: 15,
    //marginBottom: 15,
    marginLeft: 15,
    marginRight: 15,
    //borderColor: "#333333",
  },
  button_text_second: {
    color: "#333333",
  },
  button_as_link: {
    color: "#2DB0FF",
    marginTop: 15,
    //marginBottom: 15,
    marginLeft: 15,
    marginRight: 15,
  },
  input: {
    marginTop: 0.0111 * height,
    marginBottom: 0,
    marginLeft: 25,
    marginRight: 25,
  },
  input2: {
    marginTop: 0.0111 * height,
    marginBottom: 0,
  },
  image: {
    //flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
    width: "100%",
    height: "100%",
  },
  bottom: {
    //position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 50,
    justifyContent: "space-between",
  },
  card_block: {
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 5,
    marginRight: 5,
    borderColor: "#046061",
    borderWidth: 1,
  },
  fab: {
    position: "absolute",
    margin: 16,
    right: 0,
    bottom: 0,
    backgroundColor: "#046061",
  },
  drawerContent: {
    //flex: 1,
    paddingTop: Platform.OS === "android" ? 28 : 25,
  },
  preference: {
    flexDirection: "column",
    justifyContent: "space-between",
    paddingVertical: 25,
    paddingHorizontal: 16,
  },
  drawer_title: {
    color: "#FFFFFF",
    fontSize: 20,
  },
  avatar: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#069697",
  },
  avatar_icon: {
    marginTop: 7,
    marginBottom: 7,
    marginRight: 7,
    backgroundColor: "#046061",
    flex: 1,
  },
  avatar_text: {
    color: "#FFFFFF",
    fontSize: 15,
    margin: 7,
    flex: 3,
  },
  drawer_item: {
    color: "#FFFFFF",
    fontSize: 13,
    margin: 2,
  },
  activityIndicator: {
    marginTop: 7,
    marginLeft: 7,
    marginRight: 7,
  },
  chip: {
    borderWidth: 0,
    borderRadius: 0,
  },
});

export default styles;
